// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fix_backwards_compat`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiError>>
abstract class ApiError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppState>>
abstract class AppState implements RustOpaqueInterface {
  Future<Api> api();

  ArcMutexOptionSharedAppState get shared;

  set shared(ArcMutexOptionSharedAppState shared);

  Future<JsonResultSessionStatsSnapshotApiError> start({
    required String workDir,
  });

  Future<String?> workDir();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectionOptions>>
abstract class ConnectionOptions implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Json < Result < SessionStatsSnapshot , ApiError > >>>
abstract class JsonResultSessionStatsSnapshotApiError
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ListenerOptions>>
abstract class ListenerOptions implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RqbitDesktopConfig>>
abstract class RqbitDesktopConfig implements RustOpaqueInterface {
  RqbitDesktopConfigConnections get connections;

  PathBuf get defaultDownloadLocation;

  RqbitDesktopConfigDht get dht;

  RqbitDesktopConfigHttpApi get httpApi;

  RqbitDesktopConfigPersistence get persistence;

  LimitsConfig get ratelimits;

  RqbitDesktopConfigUpnp get upnp;

  set connections(RqbitDesktopConfigConnections connections);

  set defaultDownloadLocation(PathBuf defaultDownloadLocation);

  set dht(RqbitDesktopConfigDht dht);

  set httpApi(RqbitDesktopConfigHttpApi httpApi);

  set persistence(RqbitDesktopConfigPersistence persistence);

  set ratelimits(LimitsConfig ratelimits);

  set upnp(RqbitDesktopConfigUpnp upnp);

  static Future<RqbitDesktopConfig> default_() =>
      RustLib.instance.api.crateApiRqbitConfigRqbitDesktopConfigDefault();

  Future<void> validate();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RqbitDesktopConfigConnections>>
abstract class RqbitDesktopConfigConnections implements RustOpaqueInterface {
  Future<(ListenerOptions?, ConnectionOptions)> asListenerAndConnectOpts();

  bool get enableTcpListen;

  bool get enableTcpOutgoing;

  bool get enableUpnpPortForward;

  bool get enableUtp;

  int get listenPort;

  Duration get peerConnectTimeout;

  Duration get peerReadWriteTimeout;

  String get socksProxy;

  set enableTcpListen(bool enableTcpListen);

  set enableTcpOutgoing(bool enableTcpOutgoing);

  set enableUpnpPortForward(bool enableUpnpPortForward);

  set enableUtp(bool enableUtp);

  set listenPort(int listenPort);

  set peerConnectTimeout(Duration peerConnectTimeout);

  set peerReadWriteTimeout(Duration peerReadWriteTimeout);

  set socksProxy(String socksProxy);

  static Future<RqbitDesktopConfigConnections> default_() => RustLib
      .instance
      .api
      .crateApiRqbitConfigRqbitDesktopConfigConnectionsDefault();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RqbitDesktopConfigDht>>
abstract class RqbitDesktopConfigDht implements RustOpaqueInterface {
  bool get disable;

  bool get disablePersistence;

  PathBuf get persistenceFilename;

  set disable(bool disable);

  set disablePersistence(bool disablePersistence);

  set persistenceFilename(PathBuf persistenceFilename);

  static Future<RqbitDesktopConfigDht> default_() =>
      RustLib.instance.api.crateApiRqbitConfigRqbitDesktopConfigDhtDefault();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RqbitDesktopConfigHttpApi>>
abstract class RqbitDesktopConfigHttpApi implements RustOpaqueInterface {
  bool get disable;

  SocketAddr get listenAddr;

  bool get readOnly;

  set disable(bool disable);

  set listenAddr(SocketAddr listenAddr);

  set readOnly(bool readOnly);

  static Future<RqbitDesktopConfigHttpApi> default_() => RustLib.instance.api
      .crateApiRqbitConfigRqbitDesktopConfigHttpApiDefault();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RqbitDesktopConfigPersistence>>
abstract class RqbitDesktopConfigPersistence implements RustOpaqueInterface {
  bool get disable;

  bool get fastresume;

  PathBuf get filename;

  PathBuf get folder;

  set disable(bool disable);

  set fastresume(bool fastresume);

  set filename(PathBuf filename);

  set folder(PathBuf folder);

  static Future<RqbitDesktopConfigPersistence> default_() => RustLib
      .instance
      .api
      .crateApiRqbitConfigRqbitDesktopConfigPersistenceDefault();
}

class RqbitDesktopConfigUpnp {
  final bool enableServer;
  final String? serverFriendlyName;

  const RqbitDesktopConfigUpnp({
    required this.enableServer,
    this.serverFriendlyName,
  });

  static Future<RqbitDesktopConfigUpnp> default_() =>
      RustLib.instance.api.crateApiRqbitConfigRqbitDesktopConfigUpnpDefault();

  @override
  int get hashCode => enableServer.hashCode ^ serverFriendlyName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RqbitDesktopConfigUpnp &&
          runtimeType == other.runtimeType &&
          enableServer == other.enableServer &&
          serverFriendlyName == other.serverFriendlyName;
}
